enum booking_status {
  accepted
  refused
  completed
}

enum provider_service_enum {
  walking_the_dog
}

table gig_consumers {
  id serial [pk, not null, increment]
  user_id integer [not null]
  address varchar(255) [not null]
  description varchar(255) [not null]
  contact_number varchar(255) [not null]

  indexes {
    user_id [name: 'gig_consumer_user_id_idx', unique]
  }
}

table gig_providers {
  id serial [pk, not null, increment]
  user_id integer [not null]
  description varchar(255) [not null]
  contact_number varchar(255) [not null]

  indexes {
    user_id [name: 'gig_provider_user_id_idx', unique]
  }
}

table provider_services {
  id serial [pk, not null, increment]
  provider_id integer [not null]
  rating integer [not null]
  service_name provider_service_enum [not null]
  availability varchar(255) [not null]
  experience varchar(255) [not null]
  additional_info varchar(255) [not null]
  geo "geometry(point)[]" [not null]

  indexes {
    (provider_id, service_name) [name: 'provider_services_idx', unique]
  }
}

table service_bookings {
  id serial [pk, not null, increment]
  consumer_id integer [not null]
  provider_service_id integer [not null]
  geo geometry(point) [not null]
  status booking_status [not null]
  booking_date date [not null]
  contract_start_date date [not null]
  contract_end_date date [not null]
  contract_duration varchar(255) [not null]
}

ref: provider_services.provider_id - gig_providers.id

ref: service_bookings.consumer_id - gig_consumers.id

ref: service_bookings.provider_service_id - provider_services.id